// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RankedHistoryChartController from "./ranked_history_chart_controller"
application.register("ranked-history-chart", RankedHistoryChartController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
