// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import IntervalReloaderController from "./interval_reloader_controller"
import FormAutoSubmitController from "./form_auto_submit_controller"
import TimeTitleController from "./time_title_controller"
import DateLocalController from "./date_local_controller"
application.register("interval-reloader", IntervalReloaderController)
application.register("form-auto-submit", FormAutoSubmitController)
application.register("time-title", TimeTitleController)
application.register("date-local", DateLocalController)
