class Character < EnumAttribute
  names[1] = "ryu"
  names[2] = "luke"
  names[3] = "kimberly"
  names[4] = "chun_li"
  names[5] = "manon"
  names[6] = "zangief"
  names[7] = "jp"
  names[8] = "dhalsim"
  names[9] = "cammy"
  names[10] = "ken"
  names[11] = "dee_jay"
  names[12] = "lilly"
  names[13] = "aki"
  names[14] = "rashid"
  names[15] = "blanka"
  names[16] = "juri"
  names[17] = "marisa"
  names[18] = "guile"
  names[19] = "ed"
  names[20] = "e_honda"
  names[21] = "jamie"
  names[22] = "akuma"
  names[26] = "m_bison"
  names[27] = "terry"
  names[28] = "mai"
  names[254] = "random"
end
