default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["SFBUFF_DATABASE_HOST"] %>
  port: <%= ENV["SFBUFF_DATABASE_PORT"] %>
  username: <%= ENV["SFBUFF_DATABASE_USERNAME"] %>
  password: <%= ENV["SFBUFF_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: sfbuff_development

test:
  <<: *default
  database: sfbuff_test

production:
  primary: &primary_production
    <<: *default
    database: sfbuff_production
  cache:
    <<: *primary_production
    database: sfbuff_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sfbuff_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sfbuff_production_cable
    migrations_paths: db/cable_migrate
