servers:
  web:
    hosts: <%= ENV.fetch("SFBUFF_LOCAL_HOST").split %>

proxy:
  ssl: false
  hosts: <%= ENV.fetch("SFBUFF_LOCAL_HOST").split %>

env:
  clear:
    RAILS_ENV: production
    SECRET_KEY_BASE: "1234567890"
    SFBUFF_DATABASE_PASSWORD: "sfbuff"
  secret:
    - BUCKLER_EMAIL
    - BUCKLER_PASSWORD
    - BUCKLER_USER_AGENT

accessories:
  db:
    host: <%= ENV.fetch("SFBUFF_LOCAL_HOST") %>
    port: 5432
    env:
      clear:
        POSTGRES_USER: sfbuff
        POSTGRES_PASSWORD: sfbuff
      secret: []
  redis:
    host: <%= ENV.fetch("SFBUFF_LOCAL_HOST") %>
    port: 6379
